/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import business.EcoSystem;
import business.consumer.Customer;
import business.enterprise.Enterprise;
import business.useraccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author Siddhant
 */
public class CustomerTaxJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerTaxJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
   

    public CustomerTaxJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem system, Customer customer) {
        initComponents();      
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taxTextField = new javax.swing.JTextField();
        dueDateTextField = new javax.swing.JTextField();
        totalTaxBtn = new javax.swing.JButton();
        dueDateBtn = new javax.swing.JButton();

        taxTextField.setEditable(false);

        dueDateTextField.setEditable(false);

        totalTaxBtn.setText("Total Tax");
        totalTaxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTaxBtnActionPerformed(evt);
            }
        });

        dueDateBtn.setText("Due Date");
        dueDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueDateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalTaxBtn)
                    .addComponent(dueDateBtn))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(dueDateTextField))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalTaxBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dueDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDateBtn))
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalTaxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTaxBtnActionPerformed
        // TODO add your handling code here:
        taxTextField.setText(String.valueOf(userAccount.getCustomer().getTax()));
    }//GEN-LAST:event_totalTaxBtnActionPerformed

    private void dueDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueDateBtnActionPerformed
        // TODO add your handling code here:
        dueDateTextField.setText(String.valueOf(userAccount.getCustomer().getDueDate()));
        
    }//GEN-LAST:event_dueDateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dueDateBtn;
    private javax.swing.JTextField dueDateTextField;
    private javax.swing.JTextField taxTextField;
    private javax.swing.JButton totalTaxBtn;
    // End of variables declaration//GEN-END:variables
}
