/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ServicePersonRole;


import business.consumer.Service;
import business.enterprise.Enterprise;
import business.market.Product;
import business.workqueue.ServicePersonWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Siddhant
 */
public class ServicePersonProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPersonProcessWorkRequestJPanel
     */
    JPanel userProcessContainer;
    ServicePersonWorkRequest request;
    Enterprise enterprise;
    
    public ServicePersonProcessWorkRequestJPanel(JPanel userProcessContainer,Enterprise enterprise, ServicePersonWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        productToBeSentCmbBox.addItem("---");
        
        for(Product product : enterprise.getProductCatalog().getProductList()){
            productToBeSentCmbBox.addItem(product);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        productToBeSentCmbBox = new javax.swing.JComboBox();

        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        productToBeSentCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(18, 18, 18)
                        .addComponent(submitJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productToBeSentCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultJTextField))))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(productToBeSentCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton)
                    .addComponent(backJButton))
                .addContainerGap(307, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ServicePersonWorkAreaJPanel spwjp = (ServicePersonWorkAreaJPanel) component;
        spwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        String result = resultJTextField.getText();
        if ((result.isEmpty()) || (result.startsWith(" "))) {
           JOptionPane.showMessageDialog(this, "All fields are Mandatory", "Warning", JOptionPane.WARNING_MESSAGE);
           return;
       }
        
        request.setRequestResult(resultJTextField.getText());
        request.setStatus("Completed");
        JOptionPane.showMessageDialog(this, "Request Sent Successfully !!!");
        
        
        
       // Product product=new Product();
       String broughtProduct=  (String) productToBeSentCmbBox.getSelectedItem().toString();
        System.out.println(request.getEnterpriseName());
        if (request.getEnterpriseName().equalsIgnoreCase("retailer")
                || request.getEnterpriseName().equalsIgnoreCase("honda")
                || request.getEnterpriseName().equalsIgnoreCase("BMW")
                || request.getEnterpriseName().equalsIgnoreCase("toyota")) {
            if (productToBeSentCmbBox.getSelectedItem().toString().equals("---")) {
                JOptionPane.showMessageDialog(this, "Customer did not use any item!!");
            } else {
                 try{
                Service service = new Service();
                service.getProduct().setProductName(broughtProduct);
               
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                //Date date = new Date();
                Date today=Calendar.getInstance().getTime();
                String reportDate=dateFormat.format(today);
                
                Date date=dateFormat.parse(reportDate);
                service.setDate(date);
                request.getCustomer().getServiceDirectory().addService(service);
                }catch(Exception e)
                {
                    
                }
            }
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox productToBeSentCmbBox;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
