/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPersonRole;

import business.consumer.Automobile;
import business.workqueue.SalesPersonWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Siddhant
 */
public class SalesPersonProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPersonProcessWorkRequestJPanel
     */
    JPanel userProcessContainer;
    SalesPersonWorkRequest request;
    
   public SalesPersonProcessWorkRequestJPanel(JPanel userProcessContainer, SalesPersonWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        selectedModelCmbBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Selected Model:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(18, 18, 18)
                        .addComponent(submitJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedModelCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultJTextField))))
                .addGap(163, 163, 163))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resultJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedModelCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJButton)
                    .addComponent(backJButton))
                .addGap(153, 153, 153))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SalesPersonWorkAreaJPanel spwjp = (SalesPersonWorkAreaJPanel) component;
        spwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        request.setRequestResult(resultJTextField.getText());
        request.setStatus("Completed");
        Automobile automobile = new Automobile();
        automobile.setAutomobileName(selectedModelCmbBox.getSelectedItem().toString());
        request.getCustomer().getAutomobileDirectory().add(automobile);
    }//GEN-LAST:event_submitJButtonActionPerformed

private void populateComboBox(){
    if(request.getEnterpriseName().equalsIgnoreCase("r")){
        selectedModelCmbBox.addItem("Honda Civic");
        selectedModelCmbBox.addItem("Honda Captur");
        selectedModelCmbBox.addItem("Honda CRV");
        selectedModelCmbBox.addItem("Honda HRV");
    }
    
    if(request.getEnterpriseName().equalsIgnoreCase("LG")){
        selectedModelCmbBox.addItem("LG LSA5PW3A L-Pearl AC");
        selectedModelCmbBox.addItem("LG LSA3NP5A L-Nova AC");
        selectedModelCmbBox.addItem("LG LSA5NP3A1 L-Nova AC");
        selectedModelCmbBox.addItem("LG BSA18IBE Inverter AC");
        selectedModelCmbBox.addItem("LG GL-I292RPZL Refrigerator");
        selectedModelCmbBox.addItem("LG GC-J237JSNV Refrigerator");
        selectedModelCmbBox.addItem("LG GL-D221AMLL.DMLZEBN Refrigerator");
    }
    
    if(request.getEnterpriseName().equalsIgnoreCase("SAMSUNG")){
        selectedModelCmbBox.addItem("Samsung AR12JC2HATP AC");
        selectedModelCmbBox.addItem("Samsung AR18HC5TFUR AC");
        selectedModelCmbBox.addItem("Samsung AR18JC3USUQ AC");
        selectedModelCmbBox.addItem("Samsung AR12JV5NBWK AC");
        selectedModelCmbBox.addItem("Samsung RR19J21C3RJ Refrigerator");
        selectedModelCmbBox.addItem("Samsung RT34K3753S9/HL Refrigerator");
        selectedModelCmbBox.addItem("Samsung RS21HSTPN Refrigerator");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JComboBox<String> selectedModelCmbBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}